### ISSUE TITLE
Setting a Default Date doesn't seem to reflect it on the calendar

### ISSUE THREAD

**Issue by cesar-moya** [lubiepomaranczki/XamForms.Controls.Calendar#9] opened 2019-09-26 15:36 UTC
On the CalendarDemo project, try setting a specific date (either through the view model or directly to the calendar). When the calendar is displayed it still shows the current date selected even though I'm sending a different date.
`
_vm = new CalendarVM();
_vm.Date = DateTime.Now.AddDays(10);            
var c2 = new CalendarXamlView();
c2.BindingContext = _vm;
`

**Comment by lubiepomaranczki** [comment] 2019-09-27 07:18
About which property of calendar are you talking about?

**Comment by lubiepomaranczki** [comment] 2019-10-07 06:26
@mimunoz wanna take a look at it? 🙌

**Comment by mimunoz** [comment] 2019-10-07 17:43
Hi @lubiepomaranczki when I'll have some time I'll try to replicate this issue.

**Comment by mimunoz** [comment] 2019-10-08 12:24
Hi all, I've been review the behavior of the demo app. @cesar-moya All depends in the place on you set the date and the BindingContext, because like the demo does, in the App.cs, if this line we change to: `calendar.Date = DateTime.Now.AddDays(10); ` for me works well. But if you can set the Date in the code behind you must to verified the BindingContext first(because it's setted in App.cs) and then change the value using the name of the calendar control setted in xaml like App.cs does:  x:Name="CalendarXam".

` ...
        CalendarVM _calendarVM;
        public CalendarXamlView()
        {
            InitializeComponent();

			_calendarVM = (CalendarVM)BindingContext;

			if (_calendarVM == null) _calendarVM = new CalendarVM();

			ChangeDate();
		}
		void ChangeDate()
		{
                        // if this date it's not setted in the App.cs
			CalendarXam.SelectedDate = DateTime.Now.AddDays(10);
                        // _calendarVM.Date =  DateTime.Now.AddDays(10); // this not work
		}

...`

But like @cesar-moya  says, if I use the binding variable "Date" in the ViewModel, the date it's not displayed selected (the value exist, but it's not rendered).

Regards!

**Comment by lubiepomaranczki** [comment] 2019-10-08 12:29
@mimunoz do you have time to fix it, so it's actually rendered?

**Comment by mimunoz** [comment] 2019-10-08 12:39
@lubiepomaranczki I could, but I don't have enough of time this week.

**Comment by lubiepomaranczki** [comment] 2019-11-10 13:39
Hey @cesar-moya,
I am working on the issue your described and I can't reproduce it. Can you please checkout branch #9-default-date-not-bindable and check if you can still reproduce it?

**Comment by cesar-moya** [comment] 2019-11-18 20:41
Hi guys @lubiepomaranczki @mimunoz . At the moment I don't have time to look into this but i will if i get some time. Thanks for looking into the issue.

**Comment by lubiepomaranczki** [comment] 2020-06-24 20:06
I am closing this issue as it is pretty old. If you still have this problem, please reopen it.

**Closed by lubiepomaranczki** 2020-06-24 20:06 UTC
Labels: 🤔need more info
